#!/usr/bin/env sh

# Markdown, textile, and other text formats
--type-set=plaintext=.md,.mdown,.markdown,.mkdn,.textile,.txt

# Plain text CSV files
--type-set=csv=.txt,.csv,.tsv

# Rubies
--type-set=ruby=.rake,.rb, .yml

# Gems
--type-set=gemspec=.gemspec

# Sass/CSS
--type-set=css=.css
--type-set=scss=.scss,.sass,.css.sass
--type-set=sass=.scss,.sass,.css.scss

# Html Template
--type-set=haml=.haml,.html,.slim,.erb

# Coffeescript
--type-set=coffeescript=.coffee

# Ignore tmp and cache files
--ignore-dir=doc
--ignore-dir=tmp
--ignore-dir=cache
--ignore-dir=generated
--ignore-dir=coverage
--ignore-dir=vendor
--ignore-dir=i18n
--smart-case
--follow
