#!/usr/bin/env sh

# Helpers
#
alias reload='. ~/.bash_profile'
alias m='mate'
alias e='aquamacs'

# Files and directories
#
alias o='open . &'
alias texclean='rm -f *.toc *.aux *.log *.cp *.fn *.tp *.vr *.pg *.ky'
alias clean='echo -n "Really clean this directory?";
  read yorn;
  if test "$yorn" = "y"; then
     rm -fR \#* *~ .*~ *.bak .*.bak  *.tmp .*.tmp core a.out;
     echo "Cleaned.";
  else
     echo "Not cleaned.";
  fi'

alias h='history'
alias l="ls -lah"
alias ls="ls -F"
alias ll="ls -l"
alias la='ls -A'
alias c='clear'
alias dir='ls -la'
alias ld='ls -al -d * | egrep "^d"' # only subdirectories
alias lt='ls -alt | head -20' # recently changed files

# File/directory navigation
alias md='mkdir -p'
alias rd=rmdir
alias ..='cd ..'
alias ...='cd ../..'
alias mkdir='mkdir -p $1'
alias rm='rm -Rf $1'
alias sym='ln -s $2 $1'

# Directory tree - http://www.shell-fu.org/lister.php?id=209
alias dirf='find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"'

# Calendar with today highlighted - http://www.shell-fu.org/lister.php?id=210
alias tcal='cal | sed "s/^/ /;s/$/ /;s/ $(date +%e) / $(date +%e | sed '\''s/./#/g'\'') /"'

# Count files by type - http://www.shell-fu.org/lister.php?id=173
alias ftype='find ${*-.} -type f | xargs file | awk -F, '\''{print $1}'\'' | awk '\''{$1=NULL;print $0}'\'' | sort | uniq -c | sort -nr'

# Create directory and cd into that directory
function take() {
    mkdir -p "$1"
    cd "$1"
}

# Publish ssh key on remote server
function authme() {
    ssh $1 'cat >>.ssh/authorized_keys' <~/.ssh/id_rsa.pub
}

# Apache
#
alias ael='tail -f /var/log/apache2/error_log'
alias aal='tail -f /var/log/apache2/access_log'
alias ars='sudo apachectl restart'

# Processor and cpu
#
alias tu='top -o cpu' # cpu
alias tm='top -o vsize' # memory

# Git
#
alias git=hub
alias gl='git pull'
alias gp='git push'
alias gd='git diff'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch -v'
alias gs='git status'
alias gco='git checkout'
alias ungit="find . -name '.git' -exec rm -rf {} \;"
alias glog='git log --pretty=format:"%ar: %s"'

# Checkout master if no branch name given
function gco {
    if [ -z "$1" ]; then
        git checkout master
    else
        git checkout $1
    fi
}

# Bundler
#
alias b="bundle"
alias be="bundle exec"
alias bi="bundle install"
alias bu="bundle update"

# Ruby
#
alias r="rake"
alias irb='irb --simple-prompt -r irb/completion -rubygems'
alias rr="rake db:reset"
alias ts='thin start'

# Open the gem directory in your favorite editor
function gemedit {
    GEMDIR=`gem env gemdir`/gems
    $EDITOR $GEMDIR/`ls $GEMDIR | grep $1 | sort | tail -1`
}

# Open the gem's readme file in your favorite editor
function gemdoc {
    GEMDIR=`gem env gemdir`/gems
    $EDITOR $GEMDIR/`ls $GEMDIR | grep $1 | sort | less`README
}

alias qri='qri -w 106'
alias fri='fri -w 106'
alias gem?="gem list | grep $1"
alias route?="rake routes | ack $1"
alias routes="rake routes | sed -e \"1d\" -e \"s,^[^/]*,,g\" | awk '{print $1}' | uniq | sort"

# Create a new .rvmrc file and give it the name of the current directory
function rvmrc {
  echo "rvm $1@${PWD##*/} --create" > .rvmrc
}

# Rails
#
alias sc='script/console'
alias ss='script/server' # start up the beast; use "ss -d" to detach
alias sg='script/generate'
alias a='autotest -rails'
alias fix='rake spec:db:fixtures:load'
alias tl='tail -f log/development.log'
alias migrate='rake db:migrate db:test:clone'
alias rst='touch tmp/restart.txt'
alias cuke='cucumber $1'
alias remigrate='rake db:migrate --trace && rake db:migrate:redo --trace && rake db:schema:dump db:test:prepare'

# Rails console
function console  {
    if [ -f "script/console" ]; then
        script/console
    elif [ -f "script/rails" ]; then
        rails console
    elif [ -f "config.ru" ]; then
        racksh
    else
        irb --simple-prompt -r irb/completion -rubygems
    fi
}

# Database console
function dbconsole {
    if [ -f "script/server" ]; then
        script/dbconsole -p
    elif [ -f "script/rails" ]; then
        rails dbconsole  -p
    fi
}

# Rails server
function server {
    if [ -f "script/server" ]; then
        script/server
    elif [ -f "script/rails" ]; then
        rails server
    fi
}

# Run tests
function test {
    if [ -d "test" ]; then
        rake test
    elif [ -d 'spec' ]; then
        rake spec
    fi
}

# Postgres
#
alias start_postgres="launchctl load -w ~/Library/LaunchAgents/org.postgresql.postgres.plist"
alias stop_postgres="launchctl unload -w ~/Library/LaunchAgents/org.postgresql.postgres.plist"

# MySQL
#
alias start_mysql="launchctl load -w ~/Library/LaunchAgents/com.mysql.mysqld.plist"
alias stop_mysql="launchctl unload -w ~/Library/LaunchAgents/com.mysql.mysqld.plist"

# Screen
#
alias crushit='export SCREENPWD=$(pwd); /usr/bin/screen'

# Fun stuff
#

# Changing directory to code project
function work { cd ~/Workspace/$1; }
function work! { cd ~/Workspace/$1 && crushit; }

# Web server from anywhere - taken from http://gist.github.com/573586
alias serve="ruby -rwebrick -e\"s = WEBrick::HTTPServer.new(:Port => 3000, :DocumentRoot => Dir.pwd); trap('INT') { s.shutdown }; s.start\""

# Return my current ip address
alias myip="curl icanhazip.com"
