#!/bin/bash

export PATH=$HOME/bin/jruby/bin:$PATH
export PATH="~/.rbenv/shims:~/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/mysql/bin:~/dotfiles/bin:~/Workspace/taco/bin:~/Workspace/littlelines-suspenders/bin:/usr/local/pgsql/bin:/usr/bin:  $PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export MAGICK_HOME=/usr/local/include/ImageMagick
export PATH=$MAGICK_HOME/bin:$PATH
export JRUBY_OPTS="-Xcext.enabled=true"

export EMACS="/usr/local/Cellar/emacs-plus/26.1/bin/emacs"
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$HOME/.cask/bin:$PATH
export PATH="./bin:$PATH"
export PATH="$(brew --prefix qt@5.5)/bin:$PATH"
# Npm
export PATH=$HOME/.npm-packages/bin:$PATH
export PATH="/usr/local/opt/libiconv/bin:$PATH"
# Php
export PATH="/usr/local/opt/php@7.1/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/sbin:$PATH"
# Rust
export PATH="$HOME/.cargo/bin:$PATH"
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

# Node stuff
export PATH="/usr/local/opt/node@8/bin:$PATH"
export NODE_PATH="/usr/local/lib/node_modules:$NODE_PATH"
export LDFLAGS="-L/usr/local/opt/node@8/lib"
export CPPFLAGS="-I/usr/local/opt/node@8/include"
